version: '3.8'
services:
    mongo_DB:
      image: mongo:latest
      ports:
        - 2717:27017
      restart: always
      volumes:
        - /appVol:/data/db
      networks:
        - shared1

    backend:
      build: ./server
      ports:
        - 5000:5000
      environment:
        PORT: 5000
        MONGO_URL: mongodb://mongo_DB:27017/chat
        REACT_APP_IP1: 65.1.95.125
      depends_on:
        - mongo_DB
      networks:
        - shared1

    frontend:
      build: ./public
      ports:
        - 80:80
      environment:
        REACT_APP_LOCALHOST_KEY: chat-app-current-user
        REACT_APP_IP: 65.1.95.125
      depends_on:
        - backend
      networks:
        - shared1

networks:
  shared1:
